name: PR
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go

    - name: Run Golang CI Lint
      uses: golangci/golangci-lint-action@v2
